FIND_PROGRAM(LUA2DOX lua2dox)
IF(NOT LUA2DOX)
	MESSAGE(WARNING "Cannot find lua2dox. No documentation will be generated")
ENDIF()

FIND_PACKAGE(Doxygen)
IF(NOT DOXYGEN_FOUND)
	MESSAGE(WARNING "Cannot find Doxygen. No documentation will be generated")
ENDIF()

SET(Lua2Dox_INSTALL_CMAKE_SUBDIR "share/cmake/lua2dox")
SET(Lua2Dox_INSTALL_CMAKE_RIDBUS "../../..")

GET_FILENAME_COMPONENT(_DIR "${CMAKE_CURRENT_LIST_FILE}" PATH)
SET(_DIR "${_DIR}/${Lua2Dox_INSTALL_CMAKE_RIDBUS}/.")
GET_FILENAME_COMPONENT(_DIR "${_DIR}" ABSOLUTE)
SET(Lua2Dox_INSTALL_PREFIX "${_DIR}")

SET(CMAKE_MODULE_PATH "${Lua2Dox_INSTALL_PREFIX}/${Lua2Dox_INSTALL_CMAKE_SUBDIR}" "${CMAKE_MODULE_PATH}")

INCLUDE(TorchDox)

MESSAGE(STATUS "Found Lua2Dox in ${Lua2Dox_INSTALL_PREFIX}")
